version: 2
jobs:
    build:
        docker:
        - image: andreacensi/mcdp_manual:1
        resource_class: large
        steps:
        - checkout
        - run:
            name: Compile all books
            command: |
                . /project/deploy/bin/activate && make compile-native

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
