version: 2
jobs:
    build:
        docker:
        - image: andreacensi/duckuments:1
        resource_class: large
        steps:
        - checkout
        - run:
            name: Compile
            command: |
                make compile-native-ci

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
